// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMDeBL04c3UaQhZJuVJD1rZA3agUqbE4',
    appId: '1:148113514149:web:d66ff9517c29235804774c',
    messagingSenderId: '148113514149',
    projectId: 'triboo-5fcea',
    authDomain: 'triboo-5fcea.firebaseapp.com',
    storageBucket: 'triboo-5fcea.firebasestorage.app',
    measurementId: 'G-T1L8PL0TP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzija6ihf8OXUJP95_OqwvvLZdw0ADNk',
    appId: '1:148113514149:android:cb0e6d7ddcaedf8a04774c',
    messagingSenderId: '148113514149',
    projectId: 'triboo-5fcea',
    storageBucket: 'triboo-5fcea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jTiIPeiKFQd2_jHuGzxG76RgI9PGeTU',
    appId: '1:148113514149:ios:28ee5e4a076295fc04774c',
    messagingSenderId: '148113514149',
    projectId: 'triboo-5fcea',
    storageBucket: 'triboo-5fcea.firebasestorage.app',
    iosBundleId: 'com.brainiaKs.triboo',
  );

}